# jhub oauth doesn't work, when minAvailable 1 and replicas 2
pdb:
  minAvailable: 0
replicas: 1

resources:
  requests:
    cpu: "0.25"
    memory: 512Mi
  limits:
    cpu: "0.5"
    memory: 512Mi

config:
  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*
      - ^hmharshit/cn-ait.*
      - ^shishirchoudharygic/mltraining.*
      - ^hmharshit/mltraining.*
  BinderHub:
    debug: true
#    hub_url: https://notebooks-test.gesis.org/jupyter/
    hub_url: https://notebooks-test.gesis.org

    use_registry: true
    image_prefix: gesiscss/orc-example-binder-
    build_image: jupyter/repo2docker:9c559d2a
    build_node_selector:
      user: worker
    per_repo_quota: 100
    per_repo_quota_higher: 200

service:
  annotations:
    prometheus.io/scrape: 'false'
  #type: ClusterIP
  type: NodePort
  nodePort: 30193

cors: &cors
  allowOrigin: "*"

dind:
  enabled: true
  hostSocketDir: /var/run/dind_example
  hostLibDir: /var/lib/dind_example

imageCleaner:
  enabled: false

jupyterhub:
  custom:
    cors: *cors
  debug:
    enabled: true

  hub:
#    baseUrl: /jupyter/
    pdb:
      minAvailable: 0
    service:
      annotations:
        prometheus.io/scrape: 'false'

    extraConfig:
      hub_extra: |
        c.JupyterHub.redirect_to_server = False
      hub_config: |
        #c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org/jupyter/'
        c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org'
        if "cookie_options" in c.JupyterHub.tornado_settings:
          c.JupyterHub.tornado_settings["cookie_options"].update({"secure": True})
        else:
          c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)
      neverRestart: |
        c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})
      noAuthMetrics: |
        c.JupyterHub.authenticate_prometheus = False

    resources:
      requests:
        cpu: "0.25"
        memory: 512Mi
      limits:
        cpu: "0.5"
        memory: 512Mi

  proxy:
    pdb:
      minAvailable: 0
    # https://zero-to-jupyterhub.readthedocs.io/en/stable/security.html#https
    https:
      enablde: false
    service:
      #type: ClusterIP
      type: NodePort
      nodePorts:
        http: 30190
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 256Mi

  singleuser:
    nodeSelector:
      user: worker
    cpu:
      guarantee: 0.1
      limit: 0.5
    memory:
      guarantee: 512M
      limit: 512M

  scheduling:
    userScheduler:
      enabled: false
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false
