pdb:
  minAvailable: 0
replicas: 1

resources:
  requests:
    cpu: "0.25"
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

config:
  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*
      - ^hmharshit/cn-ait.*
      - ^shishirchoudharygic/mltraining.*
      - ^hmharshit/mltraining.*
  BinderHub:
    debug: true
    hub_url: https://notebooks-test.gesis.org
    use_registry: true
    image_prefix: gesiscss/orc-example-binder-
    build_image: jupyter/repo2docker:0.10.0-112.g242107b
    build_node_selector:
      user: worker
    per_repo_quota: 100
    per_repo_quota_higher: 200

service:
  annotations:
    prometheus.io/scrape: 'false'
  type: NodePort
  nodePort: 30193

cors: &cors
  allowOrigin: "*"

dind:
  enabled: true
  hostSocketDir: /var/run/dind_example
  hostLibDir: /var/lib/dind_example

imageCleaner:
  enabled: false

jupyterhub:
  custom:
    cors: *cors
  debug:
    enabled: true

  hub:
    pdb:
      minAvailable: 0
    nodeSelector:
      base: worker
    service:
      annotations:
        prometheus.io/scrape: 'false'

    redirectToServer: false
    authenticatePrometheus: false
    shutdownOnLogout: true
    extraConfig:
      neverRestart: |
        c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})
      bind_url: |
        c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org'
      hub_config: |
        if "cookie_options" in c.JupyterHub.tornado_settings:
          c.JupyterHub.tornado_settings["cookie_options"].update({"secure": True})
        else:
          c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)

    resources:
      requests:
        cpu: "0.25"
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

  proxy:
    pdb:
      minAvailable: 0
    https:
      enablde: false
    service:
      type: NodePort
      nodePorts:
        http: 30190
    chp:
      resources:
        requests:
          cpu: "0.5"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi

  singleuser:
    nodeSelector:
      user: worker
    cpu:
      guarantee: 0.1
      limit: 0.5
    memory:
      guarantee: 512M
      limit: 1G

  scheduling:
    userScheduler:
      enabled: false
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false
