binderhub:
  pdb:
    minAvailable: 0
  replicas: 1
  resources:
    requests:
      cpu: "0.25"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  config:
    BinderHub:
      debug: true
      hub_url: https://notebooks-test.gesis.org
      per_repo_quota: 100
      per_repo_quota_higher: 200
      use_registry: true
      image_prefix: gesiscss/orc-example-binder-
      build_image: jupyter/repo2docker:0.10.0-123.gf79bf04
      build_node_selector:
        user: worker

  service:
    annotations:
      prometheus.io/scrape: 'false'
    type: NodePort
    nodePort: 30193

  cors: &cors
    allowOrigin: "*"

  dind:
    enabled: true
    hostSocketDir: /var/run/dind_example
    hostLibDir: /ssd/dind_example

  imageCleaner:
    enabled: false

  jupyterhub:
    custom:
      cors: *cors
    debug:
      enabled: true

    hub:
      pdb:
        minAvailable: 0
      nodeSelector:
        base: worker
      service:
        annotations:
          prometheus.io/scrape: 'false'
      redirectToServer: false
      authenticatePrometheus: false
      shutdownOnLogout: true
      extraConfig:
        01-hub: |
          if "cookie_options" in c.JupyterHub.tornado_settings:
            c.JupyterHub.tornado_settings["cookie_options"].update({"secure": True})
          else:
            c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)
        02-never-restart: |
          c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})
      resources:
        requests:
          cpu: "0.25"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi

    proxy:
      pdb:
        minAvailable: 0
      https:
        enablde: false
      service:
        type: NodePort
        nodePorts:
          http: 30190
      chp:
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi

    singleuser:
      nodeSelector:
        user: worker
      cpu:
        guarantee: 0.1
        limit: 0.5
      memory:
        guarantee: 512M
        limit: 1G

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: false
      userPlaceholder:
        enabled: false
