apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 30176
  - name: https
    protocol: TCP
    targetPort: 443
    port: 443
    nodePort: 30177
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      nodeSelector:
        staging: worker
      containers:
      - name: nginx
        image: nginx:1.13.6
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        resources:
          requests:
            cpu: "0.25"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: letsencrypt-volume
          mountPath: "/etc/letsencrypt_volume"
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-configmap
      - name: letsencrypt-volume
        hostPath:
          path: /etc/letsencrypt